name: "CI / Feature"

on:
  push:
    branches:
      - feature*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  use-native-library-js-feature:
    permissions:
      contents: read
      actions: write
      checks: write
    uses: MatrixAI/.github/.github/workflows/native-library-js-feature.yml@master
