name: "CI / Staging"

on:
  push:
    branches:
      - staging
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  use-native-library-js-staging:
    permissions:
      contents: write
      actions: write
      checks: write
      pull-requests: write
    uses: MatrixAI/.github/.github/workflows/native-library-js-staging.yml@master
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
      GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
      GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
      GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}

