name: "CI / Tag"

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  use-native-library-js-tag:
    permissions:
      contents: read
      actions: write
      checks: write
    uses: MatrixAI/.github/.github/workflows/native-library-js-tag.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
